title: "Portfolio"
#logo: "/assets/img/102557818.jpg"
author:
  name     : "Cristian Percivati"
  avatar   : "/assets/img/102557818.jpg"
description: "Welcome to my portfolio!"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
